spring.application.name=api
spring.data.mongodb.uri=mongodb+srv://admin:admin123@cluster0.mongodb.net/smart-campus?retryWrites=true&w=majority
server.port=8080

# JWT Configuration
app.jwtSecret=926D96C90030DD58429D31923847263643D7492434A4D617653535664586E3272
app.jwtExpirationInMs=604800000

# Logging
logging.level.org.springframework.security=DEBUG

# OAuth2 Google Setup
spring.security.oauth2.client.registration.google.client-id=YOUR_GOOGLE_CLIENT_ID
spring.security.oauth2.client.registration.google.client-secret=YOUR_GOOGLE_CLIENT_SECRET
spring.security.oauth2.client.registration.google.scope=email,profile
# Important for React App: Where to redirect after success
app.oauth2.authorizedRedirectUris=http://localhost:5173/oauth2/redirect
