spring.application.name=api
server.port=8081

spring.data.mongodb.uri=mongodb+srv://admin23:admin123@cluster0.noan6i7.mongodb.net/smartcampus?authSource=admin

jwt.secret=94a08da1fecb6e4b23d9bba4c4e0b57e7939b4b92b6a7a5e4d29188e6a1c51d6
jwt.expiration=86400000
