@echo off
echo Stopping any process on port 8081...
for /f "tokens=5" %%a in ('netstat -aon ^| find ":8081"') do taskkill /F /PID %%a 2>nul
timeout /t 2 /nobreak > nul
echo Starting backend...
call mvnw spring-boot:run
